# Generated by Django 2.2.1 on 2019-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
