# Generated by Django 2.2.1 on 2019-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190525_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
