# Generated by Django 2.2.1 on 2019-06-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policestation',
            old_name='place',
            new_name='name',
        ),
    ]
