# Generated by Django 2.2.1 on 2019-05-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0002_accidents_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidents',
            name='customer',
        ),
        migrations.AddField(
            model_name='accidents',
            name='vehicle',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
