# Generated by Django 2.2.1 on 2019-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0004_auto_20190525_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='cell_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accident',
            name='lac',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accident',
            name='mcc',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accident',
            name='mnc',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accident',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='occurrence',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
