# Generated by Django 2.2.1 on 2019-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0005_auto_20190527_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='acc_x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accident',
            name='accident_type',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accident',
            name='ultra_son_dist',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
